theme: minima
title: intelligent document processing with openai & langchain
description: Build a production-ready AI document extraction system using OpenAI, LangChain, FastAPI, Pydantic, MongoDB and Python

header_pages:
  - index.md
  - 1_setup_env/index.md
  - 2_mongodb/index.md
  - 3_fastapi/index.md
  - 4_langchain_/index.md
